FROM ubuntu:20.04
ENV TZ=Etc/GMT
RUN apt-get update \
    && apt-get install -y python3 \
    && apt-get install -y git \
    && apt-get install -y curl \
    && apt-get install -y vim \
    && apt-get install -y bash-completion \
    && apt-get install -y net-tools \
    && apt-get install -y iputils-ping 
